
package cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JogoAritmetico", targetNamespace = "http://servidor/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JogoAritmetico {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlacar", targetNamespace = "http://servidor/", className = "cliente.GetPlacar")
    @ResponseWrapper(localName = "getPlacarResponse", targetNamespace = "http://servidor/", className = "cliente.GetPlacarResponse")
    @Action(input = "http://servidor/JogoAritmetico/getPlacarRequest", output = "http://servidor/JogoAritmetico/getPlacarResponse")
    public String getPlacar();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDesafio", targetNamespace = "http://servidor/", className = "cliente.GetDesafio")
    @ResponseWrapper(localName = "getDesafioResponse", targetNamespace = "http://servidor/", className = "cliente.GetDesafioResponse")
    @Action(input = "http://servidor/JogoAritmetico/getDesafioRequest", output = "http://servidor/JogoAritmetico/getDesafioResponse")
    public String getDesafio();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrar", targetNamespace = "http://servidor/", className = "cliente.Registrar")
    @ResponseWrapper(localName = "registrarResponse", targetNamespace = "http://servidor/", className = "cliente.RegistrarResponse")
    @Action(input = "http://servidor/JogoAritmetico/registrarRequest", output = "http://servidor/JogoAritmetico/registrarResponse")
    public void registrar(
        @WebParam(name = "arg0", targetNamespace = "")
        Cliente arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterStatus", targetNamespace = "http://servidor/", className = "cliente.ObterStatus")
    @ResponseWrapper(localName = "obterStatusResponse", targetNamespace = "http://servidor/", className = "cliente.ObterStatusResponse")
    @Action(input = "http://servidor/JogoAritmetico/obterStatusRequest", output = "http://servidor/JogoAritmetico/obterStatusResponse")
    public int obterStatus();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "putResposta", targetNamespace = "http://servidor/", className = "cliente.PutResposta")
    @ResponseWrapper(localName = "putRespostaResponse", targetNamespace = "http://servidor/", className = "cliente.PutRespostaResponse")
    @Action(input = "http://servidor/JogoAritmetico/putRespostaRequest", output = "http://servidor/JogoAritmetico/putRespostaResponse")
    public boolean putResposta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Cliente arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setStatus", targetNamespace = "http://servidor/", className = "cliente.SetStatus")
    @ResponseWrapper(localName = "setStatusResponse", targetNamespace = "http://servidor/", className = "cliente.SetStatusResponse")
    @Action(input = "http://servidor/JogoAritmetico/setStatusRequest", output = "http://servidor/JogoAritmetico/setStatusResponse")
    public void setStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "runCommand", targetNamespace = "http://servidor/", className = "cliente.RunCommand")
    @ResponseWrapper(localName = "runCommandResponse", targetNamespace = "http://servidor/", className = "cliente.RunCommandResponse")
    @Action(input = "http://servidor/JogoAritmetico/runCommandRequest", output = "http://servidor/JogoAritmetico/runCommandResponse")
    public void runCommand(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
