
package cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JogoAritmeticoService", targetNamespace = "http://servidor/", wsdlLocation = "http://localhost:8080/WebServices/jogo?wsdl")
public class JogoAritmeticoService
    extends Service
{

    private final static URL JOGOARITMETICOSERVICE_WSDL_LOCATION;
    private final static WebServiceException JOGOARITMETICOSERVICE_EXCEPTION;
    private final static QName JOGOARITMETICOSERVICE_QNAME = new QName("http://servidor/", "JogoAritmeticoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServices/jogo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JOGOARITMETICOSERVICE_WSDL_LOCATION = url;
        JOGOARITMETICOSERVICE_EXCEPTION = e;
    }

    public JogoAritmeticoService() {
        super(__getWsdlLocation(), JOGOARITMETICOSERVICE_QNAME);
    }

    public JogoAritmeticoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JOGOARITMETICOSERVICE_QNAME, features);
    }

    public JogoAritmeticoService(URL wsdlLocation) {
        super(wsdlLocation, JOGOARITMETICOSERVICE_QNAME);
    }

    public JogoAritmeticoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JOGOARITMETICOSERVICE_QNAME, features);
    }

    public JogoAritmeticoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JogoAritmeticoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JogoAritmetico
     */
    @WebEndpoint(name = "JogoAritmeticoPort")
    public JogoAritmetico getJogoAritmeticoPort() {
        return super.getPort(new QName("http://servidor/", "JogoAritmeticoPort"), JogoAritmetico.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JogoAritmetico
     */
    @WebEndpoint(name = "JogoAritmeticoPort")
    public JogoAritmetico getJogoAritmeticoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servidor/", "JogoAritmeticoPort"), JogoAritmetico.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JOGOARITMETICOSERVICE_EXCEPTION!= null) {
            throw JOGOARITMETICOSERVICE_EXCEPTION;
        }
        return JOGOARITMETICOSERVICE_WSDL_LOCATION;
    }

}
